server:
  port: 8081

spring:
  application:
    name: kbs-mcp
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        protocol: streamable
        type: sync
        streamable-http:
          mcp-endpoint: /${spring.application.name}

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kbs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      # 最大连接数，cpu核心数 * 2
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      transaction-isolation:

